/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
public class UserRole implements Serializable {

    /*@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("userRoleId")
    private Long userRoleId;*/

    @Column(name = "ID", table = "USERROLE", nullable = false)
    @Id
    @FormParam("userRoleId")
    private Integer userRoleId;

    @ManyToOne(targetEntity = Role.class)
    private Role role1;

    @ManyToOne(targetEntity = User.class)
    private User user1;

    public Integer getId() {
        return this.userRoleId;
    }

    public void setId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    public Role getRole1() {
        return this.role1;
    }

    public void setRole1(Role role1) {
        this.role1 = role1;
    }

    public User getUser1() {
        return this.user1;
    }

    public void setUser1(User user1) {
        this.user1 = user1;
    }

}
